/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Julian
 */
public class Ventana extends javax.swing.JFrame {

    private String promedio;

    /**
     * Creates new form NewJFrame
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agregarDato = new javax.swing.JButton();
        numeroIngresado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        posicionIngresada = new javax.swing.JTextField();
        borrarDato = new javax.swing.JButton();
        limpiarArreglo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        salidaGeneral = new javax.swing.JLabel();
        consultarArreglo = new javax.swing.JButton();
        calcularPromedio = new javax.swing.JButton();
        salidaPromedio = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregarDato.setText("Agregar");
        agregarDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDatoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese un número");

        jLabel2.setText("Ingrese posición");

        posicionIngresada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posicionIngresadaActionPerformed(evt);
            }
        });

        borrarDato.setText("Borrar");
        borrarDato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarDatoActionPerformed(evt);
            }
        });

        limpiarArreglo.setText("Limpiar Arreglo");
        limpiarArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarArregloActionPerformed(evt);
            }
        });

        jLabel3.setText("Salida de datos:");

        salidaGeneral.setText("- - - - - - - - - -");

        consultarArreglo.setText("Consultar Arreglo");
        consultarArreglo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarArregloActionPerformed(evt);
            }
        });

        calcularPromedio.setText("Calcular Promedio");
        calcularPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularPromedioActionPerformed(evt);
            }
        });

        salidaPromedio.setText("salida");

        jLabel4.setText("Julian Felipe Parra Pulido");

        jLabel5.setText("1020802008");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numeroIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(posicionIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agregarDato, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(borrarDato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(limpiarArreglo)
                                .addGap(18, 18, 18)
                                .addComponent(consultarArreglo))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3)
                        .addGap(32, 32, 32)
                        .addComponent(salidaGeneral))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(calcularPromedio)
                        .addGap(18, 18, 18)
                        .addComponent(salidaPromedio))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel4)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroIngresado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agregarDato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posicionIngresada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrarDato))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(limpiarArreglo)
                    .addComponent(consultarArreglo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcularPromedio)
                    .addComponent(salidaPromedio))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(salidaGeneral))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int numero;
    int posicion;
    int[] arreglo = new int[10];
    private void agregarDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDatoActionPerformed
        // TODO add your handling code here:
        numero = Integer.parseInt(numeroIngresado.getText());
        posicion = Integer.parseInt(posicionIngresada.getText());
        arreglo[posicion] = numero;
    }//GEN-LAST:event_agregarDatoActionPerformed

    private void posicionIngresadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posicionIngresadaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_posicionIngresadaActionPerformed

    private void borrarDatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarDatoActionPerformed
        // TODO add your handling code here:
        numero = Integer.parseInt(numeroIngresado.getText());
        posicion = Integer.parseInt(posicionIngresada.getText());
        arreglo[posicion] = 0;
    }//GEN-LAST:event_borrarDatoActionPerformed

    private void limpiarArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarArregloActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < arreglo.length; i++) {
            arreglo[i] = 0;
        }

    }//GEN-LAST:event_limpiarArregloActionPerformed

    private void consultarArregloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarArregloActionPerformed
        // TODO add your handling code here:
//        for (int i = 0; i < 10; i++) {
            salidaGeneral.setText(arreglo[0] + "," +  arreglo[1] + ","  +  arreglo[2] + ","
                     +  arreglo[3] + ","  +  arreglo[4] + "," +  arreglo[5] + ","
                     +  arreglo[6] + ","  +  arreglo[7] + ","  +  arreglo[8] + ","
                     +  arreglo[9] + ","
                );
        //}
        
    }//GEN-LAST:event_consultarArregloActionPerformed

    private void calcularPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularPromedioActionPerformed
        // TODO add your handling code here:
        int suma=0;
        double promedio;
        for (int i = 0; i < arreglo.length; i++) {
            suma+=arreglo[i];
        }
        promedio=suma/arreglo.length;
        salidaPromedio.setText(String.valueOf(promedio));
    }//GEN-LAST:event_calcularPromedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarDato;
    private javax.swing.JButton borrarDato;
    private javax.swing.JButton calcularPromedio;
    private javax.swing.JButton consultarArreglo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton limpiarArreglo;
    private javax.swing.JTextField numeroIngresado;
    private javax.swing.JTextField posicionIngresada;
    private javax.swing.JLabel salidaGeneral;
    private javax.swing.JLabel salidaPromedio;
    // End of variables declaration//GEN-END:variables
}
